version: '3.8'

services:
  db:
    image: postgres:16 # Use a specific version, e.g., PostgreSQL 16
    container_name: vibe_db
    restart: always
    environment:
      POSTGRES_USER: user # Define your database user
      POSTGRES_PASSWORD: password # Define your database password
      POSTGRES_DB: vibe_dev # Define your database name
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data # Persist data in a bind mount

volumes:
  postgres_data: # Define the named volume 